Marylin/whack a mole
MinionsGroup/devfund-h pull request #22
Opened 2018-07-13 01:40 UTC by marylin-moya

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +        for (int i = numAttemps; i > 0; i++) {
![BLOCKER](https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER') Correct this loop's end condition. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2189)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') "i" is incremented and will never reach "stop condition". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2251)
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Reduce the total number of break and continue statements in this loop to use at most one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS135)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +            System.out.print("Enter the x coordinates: ");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +                    System.out.print("*  ");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +            System.out.print("Enter the y coordinates: ");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +                    System.out.print(this.moleGrid[i][j] + "  ");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +            System.out.println("");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +                System.out.println("Giving up!!");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +                System.out.println("There is already a mole at " + x + "," + y + ". Trying again!");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +                i--;
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Refactor the code in order to not assign to this loop counter from within the loop body. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AForLoopCounterChangedCheck)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +                System.out.println("State of Game");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +                System.out.println("Mole places at " + x + "," + y);
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +                System.out.print(this.moleGrid[i][j] + "  ");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +                System.out.println("All moles were whacked with score: " + whackAMole.score);
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +            System.out.println("");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +        System.out.println("----------------------------");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +                System.out.println("There are no more attemps with score: " + whackAMole.score);
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +        System.out.println("-----You have a maximum of " + numAttemps + " attempts to get all the moles wacked-----");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 01:42 UTC, carledriss commented
SonarQube analysis reported 19 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 16 minor

Watch the comments in this conversation to review them.

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-07-13 02:32 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +        for (int i = numAttemps; i > 0; i--) {
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Reduce the total number of break and continue statements in this loop to use at most one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS135)

2018-07-13 02:32 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +            System.out.print("Enter the x coordinates: ");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-13 02:32 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +            LOGGER.info(strBuilderRow.toString());
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Invoke method(s) only conditionally. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2629)

2018-07-13 02:32 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +            LOGGER.info(strBuilderRow.toString());
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Invoke method(s) only conditionally. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2629)

2018-07-13 02:32 UTC, carledriss commented
SonarQube analysis reported 14 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 11 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-07-13 02:56 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +            LOGGER.info(strBuilderMessage.toString());
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Invoke method(s) only conditionally. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2629)

2018-07-13 02:56 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +                LOGGER.info("All moles were whacked with score: " + whackAMole.score);
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Use the built-in formatting to construct this argument. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2629)

2018-07-13 02:56 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +                LOGGER.info("There are no more attemps with score: " + whackAMole.score);
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Use the built-in formatting to construct this argument. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2629)

2018-07-13 02:56 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +                i--;
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Refactor the code in order to not assign to this loop counter from within the loop body. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AForLoopCounterChangedCheck)

2018-07-13 02:56 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +        LOGGER.info("-----You have a maximum of " + numAttemps + " attempts to get all the moles wacked-----");
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Use the built-in formatting to construct this argument. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2629)

2018-07-13 02:56 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +            LOGGER.info(strBuilderRow.toString());
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Invoke method(s) only conditionally. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2629)

2018-07-13 02:56 UTC, carledriss commented
SonarQube analysis reported 8 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-07-13 14:03 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +            LOGGER.fine(strBuilderMessage.toString());
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Invoke method(s) only conditionally. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2629)

2018-07-13 14:03 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +            LOGGER.fine(strBuilderRow.toString());
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Invoke method(s) only conditionally. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2629)

2018-07-13 14:03 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +            LOGGER.fine(strBuilderRow.toString());
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Invoke method(s) only conditionally. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2629)

2018-07-13 14:03 UTC, carledriss commented
SonarQube analysis reported 5 issues
* ![MAJOR][MAJOR] 4 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-07-13 15:29 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +    private void printGridToUser() {
In order to test printGridToUser method
You should return a String

2018-07-13 15:29 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +    private void printGrid() {
In order to test printGridToUser method
You should return a String

2018-07-13 15:30 UTC, carledriss commented on src/main/java/org/minions/devfund/marylin/WhackAMole.java
> +    public static void main(final String[] args) {
Since edx doesn't require this method.
You could remove it!

2018-07-13 21:47 UTC, marylin-moya commented
![week1_progress](https://user-images.githubusercontent.com/9888530/42715397-db027860-86c4-11e8-80d7-b8c861e44716.png)
![week1_wackamolle_report](https://user-images.githubusercontent.com/9888530/42715402-ddf11bc6-86c4-11e8-9e29-df0244a90cea.png)

2018-07-16 21:42 UTC, carledriss requested changes
Fix findbugs issues.

2018-07-19 13:32 UTC, carledriss approved these changes
LGTM! 👍

2018-07-19 13:33 UTC, merged