Damianvp/whack a mole
MinionsGroup/devfund-h pull request #42
Opened 2018-07-21 05:05 UTC by Dam24

Whack a Mole game task

2018-07-21 05:07 UTC, carledriss commented on src/main/java/org/minions/devfund/damianvp/WhackAMole.java
> +            System.out.println("Great you win!!!");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-21 05:07 UTC, carledriss commented on src/main/java/org/minions/devfund/damianvp/WhackAMole.java
> +        System.out.println("Is not possible place more than fdsfsdf");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-21 05:07 UTC, carledriss commented on src/main/java/org/minions/devfund/damianvp/WhackAMole.java
> +            System.out.println(String.format("Score: %s", this.score));
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-21 05:07 UTC, carledriss commented on src/main/java/org/minions/devfund/damianvp/WhackAMole.java
> +        System.out.println(Arrays.deepToString(this.moleGrid));
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-21 05:07 UTC, carledriss commented on src/main/java/org/minions/devfund/damianvp/WhackAMole.java
> +            System.out.println("You Loss...  Try Again");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-21 05:07 UTC, carledriss commented on src/main/java/org/minions/devfund/damianvp/WhackAMole.java
> +            System.out.println(String.format("valid coordinates should be between 0 - %s", this.moleGrid.length - 1));
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-21 05:07 UTC, carledriss commented on src/main/java/org/minions/devfund/damianvp/WhackAMole.java
> +                System.out.println("Good, you found a mole!!");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-21 05:07 UTC, carledriss commented on src/main/java/org/minions/devfund/damianvp/WhackAMole.java
> +        System.out.println(Arrays.deepToString(this.trackerMoleGrid));
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-07-21 05:07 UTC, carledriss commented on src/test/java/org/minions/devfund/damianvp/WhackAMoleTest.java
> +//        assertTrue(whackAMoleGame.place());
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') This block of commented-out lines of code should be removed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

2018-07-21 05:07 UTC, carledriss commented on src/test/java/org/minions/devfund/damianvp/WhackAMoleTest.java
> +//        WhackAMole game = startNewGame(4,4);
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') This block of commented-out lines of code should be removed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

2018-07-21 05:07 UTC, carledriss commented
SonarQube analysis reported 10 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 8 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-07-23 23:44 UTC, carledriss commented on src/main/java/org/minions/devfund/damianvp/WhackAMole.java
> +        LOGGER.log(Level.INFO, Arrays.deepToString(this.trackerMoleGrid));
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Invoke method(s) only conditionally. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2629)

2018-07-23 23:44 UTC, carledriss commented on src/main/java/org/minions/devfund/damianvp/WhackAMole.java
> +        LOGGER.log(Level.INFO, Arrays.deepToString(this.moleGrid));
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Invoke method(s) only conditionally. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2629)

2018-07-23 23:44 UTC, carledriss commented
SonarQube analysis reported 2 issues
* ![MAJOR][MAJOR] 2 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2018-07-24 20:16 UTC, carledriss requested changes
This PR should only have WackAMole classes

2018-07-24 20:33 UTC, carledriss requested changes

2018-07-24 20:33 UTC, carledriss commented on src/test/java/org/minions/devfund/damianvp/WhackAMoleTest.java
> +    public void testPlaceMoleValidPositions() {
Please write your unit tests like edx
You should have the same quantity of unit tests

2018-07-26 12:11 UTC, sphinix27 requested changes
Increase code coverage.

2018-07-26 12:11 UTC, sphinix27 commented on src/main/java/org/minions/devfund/damianvp/WhackAMole.java
> +                if (moleIsPlaced) {
You can remove the Boolean and just use the method, the var is not used elsewhere.
```java
if (place(x,y)) {
     moles--;
}
```

2018-07-26 12:11 UTC, sphinix27 commented on src/main/java/org/minions/devfund/damianvp/WhackAMole.java
> +        } else {
You can remove the else and just put the Logger and return false after the if condition.

2018-07-30 23:46 UTC, closed without merging